### ISSUE TITLE
Refactor Policy Engine 

### ISSUE THREAD

**Issue by yusufsheiqh** [ministryofjustice/network-access-control-server#112]
## User Story

As a software engineer
I want to keep the codebase for the policy engine as simple as possible.  
So that it is easy to change in the future.

## Value / Purpose

Method extraction refactoring to make the Policy Engine easy to maintain.

## Useful Contacts

emile@madetech.com

## Definition of Done
The policy engine has been refactored with new named functions

**Comment by mitchdawson1982** [comment]
Relates specifically to the python code written for the policy engine, remove reliance on the single function, break out into methods or smaller decoupled functions.

**Comment by mitchdawson1982** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/network-access-control-server/112?planning-poker) with ZenHub @ASTRobinson @bagg3rs @emileswarts @Gary-H9 @kyphutruong @moontune @mTouhid @wanieldilson
