### ISSUE TITLE
✨ Add ability to identify device type

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/network-access-control-server#144]
### User Story

As a… Network Administrator
I need/want/expect to… be able to create policy rules based on device types (laptops, printers etc) 
So that… I can manage devices more effectively 

### Value / Purpose

This will enable easier device management for policy configuration.

### Useful Contacts

Matti, Yusuf, Emile, Gaz

### Additional Information

EUC team are able to include the following information in the SAN fields of a client certificate. Example:

```
DNS.1=moj.test.org.uk
DNS.2=laptop.moj.test.org.uk
```

This can be used in our solution.

### Definition of Done

- [x] Satisfies User Story
- [x] Test coverage (Matti)
- [x] Test coverage (RSpec)
- [x] documentation updated 
- [ ] production approved

**Comment by ASTRobinson** [comment]
raise change request for release to production

**Comment by ASTRobinson** [comment]
released to production via the pipeline on Nov 11, 2022 9:50 AM (UTC±0:00)
